### ISSUE TITLE
Intermittent issue with Regex Prompt

### ISSUE THREAD

**Issue by davidbram** [Ara225/regex-copy-or-cut#11]
**My Setup Details**

- MacOS Sonoma 14.5
- VSCode 1.19.2
- Regex Copy or Cut version 1.0.0 (only available version to install)

**Issue:** 
The keyboard shortcut `Ctrl + Alt (Option) + C`, `Ctrl + Shift + C` etc. intermittently fails to bring up the regex prompt. Sometimes it works as expected, prompting me to enter a regex, but other times the prompt does not appear at all.
I've tried restarting VSCode but it doesn't help.

**Comment by Ara225** [comment]
Hiya 
I've found that this happens when the find and replace box is open or any other dialogue box is opening that the case for you?

**Comment by davidbram** [comment]
<img width="1438" alt="Screenshot 2024-08-25 at 10 45 31 PM" src="https://github.com/user-attachments/assets/096a6b3d-2496-4d0e-b7ab-9ae34509a56c">

Nope, in my case, there isn't any dialog box open, but the regex prompt still doesn't appear.

**Comment by Ara225** [comment]
Intresting have you noticed a pattern at all? What other extensions do you have installed?

**Comment by davidbram** [comment]
Now that you mention it, I've noticed a pattern: the Regex prompt consistently appears for files with extensions like `.log` or `.csv`. However, when dealing with files without an extension, it appears intermittently.

**Comment by davidbram** [comment]
My VSCode Extensions

```
ara225.regex-copy-or-cut
dbaeumer.vscode-eslint
dsznajder.es7-react-js-snippets
eamodio.gitlens
editorconfig.editorconfig
erikphansen.vscode-toggle-column-selection
esbenp.prettier-vscode
file-icons.file-icons
formulahendry.auto-close-tag
funkyremi.vscode-google-translate
glenn2223.live-sass
hashicorp.terraform
hex-ci.stylelint-plus
humao.rest-client
mechatroner.rainbow-csv
mhutchie.git-graph
mikestead.dotenv
mohsen1.prettify-json
ms-azuretools.vscode-docker
ms-python.autopep8
ms-python.debugpy
ms-python.isort
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.vscode-jupyter-cell-tags
ms-toolsai.vscode-jupyter-slideshow
ms-vscode-remote.remote-containers
ms-vsliveshare.vsliveshare
naumovs.color-highlight
postman.postman-for-vscode
redhat.vscode-yaml
ritwickdey.liveserver
timvaneker.serverless-snippets
wallabyjs.quokka-vscode
xabikos.javascriptsnippets
zhuangtongfa.material-theme
```

**Comment by Ara225** [comment]
Thanks for that. For me only the  Ctrl + Alt (Option) + C variant seems to be broken, and I get a validation Failed notification Is that's what's happening for you?

**Comment by Ara225** [comment]
Found the problem. Another extention is registering the same shortcut on start up so whether it works depends on what ext gets to it first. You can change the shortcuts yourself in the vscode keyboard shortcuts settings page or disable the other ext if you don't need it. That fixes it.
![Capture1](https://github.com/user-attachments/assets/f37d4788-be66-47c1-bd2b-663f35b1359a)

**Comment by davidbram** [comment]
I don't see a validation failed notification 

For me the 'Copy Lines matching Regex Pattern and Paste Into New document' is the only command registered with `Ctrl + Option + C` shortcut.

<img width="1143" alt="Screenshot 2024-08-30 at 6 26 53 AM" src="https://github.com/user-attachments/assets/cca38bc9-d20a-4d83-9931-bfdafa44ce6f">

I've been able to work around this by adding an extension to all files.  

Btw, it's a very helpful extension.

**Comment by Ara225** [comment]
That really is extremely odd, I imagine it is probably that ext messing with it since it clearly wants that shortcut, but maybe it doesn't behave quite the same on Mac as it does on Windows. If it is, another workaround would be changing the language of the file. 

Anyway glad you've found a workaround, and that you're finding it useful
